# Generated by Django 3.1 on 2020-09-16 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toleName', models.CharField(max_length=60)),
                ('municipalityWarNo', models.SmallIntegerField()),
                ('district', models.CharField(max_length=60)),
                ('provinceName', models.CharField(max_length=60)),
                ('countryName', models.CharField(max_length=60)),
                ('modifiedDate', models.DateTimeField()),
                ('isPermanent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.BigIntegerField()),
                ('minutes', models.BigIntegerField()),
                ('minimumCost', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(max_length=100, null=True)),
                ('noofParkingSpots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.BigIntegerField()),
                ('isCreditedUser', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('phoneNo', models.BigIntegerField(unique=True)),
                ('citizinshipNo', models.CharField(max_length=100, null=True, unique=True)),
                ('isValidated', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isOccupied', models.BooleanField()),
                ('parkingStation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spsmain.parkingstation')),
            ],
        ),
        migrations.CreateModel(
            name='OccupiedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationEndTime', models.DateField()),
                ('occupiedBy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parkingSpot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spsmain.parkingspot')),
            ],
        ),
    ]
