# Generated by Django 3.1 on 2020-09-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='isCreditedUser',
            new_name='isCreditedToUser',
        ),
        migrations.AddField(
            model_name='transaction',
            name='eventHandler',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='models',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='productIdentity',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='productList',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='productName',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
