# Generated by Django 3.1 on 2020-09-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spsmain', '0002_auto_20200916_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='isOccupied',
        ),
        migrations.AddField(
            model_name='parkingcost',
            name='parkingSpot',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='spsmain.parkingspot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingstation',
            name='noofParkingSpots',
            field=models.IntegerField(null=True),
        ),
    ]
