# Generated by Django 3.1 on 2020-09-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spsmain', '0003_auto_20200919_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingstation',
            name='noofParkingSpots',
        ),
    ]
