# Generated by Django 3.1 on 2020-09-19 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spsmain', '0004_remove_parkingstation_noofparkingspots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupiedstatus',
            name='occupiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parkingcost',
            name='parkingSpot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spsmain.parkingspot'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='parkingStation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spsmain.parkingstation'),
        ),
    ]
