# Generated by Django 3.1 on 2020-09-19 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spsmain', '0005_auto_20200919_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='occupiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='reservationEndTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='OccupiedStatus',
        ),
    ]
