# Generated by Django 3.1 on 2020-09-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsmain', '0006_auto_20200919_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='reservationEndTime',
            field=models.DateTimeField(null=True),
        ),
    ]
