# Generated by Django 3.1 on 2020-09-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsmain', '0007_auto_20200922_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='models',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
