# Generated by Django 3.1 on 2020-09-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsmain', '0008_auto_20200923_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
