# Generated by Django 3.1 on 2020-10-02 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spsmain', '0009_auto_20200926_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingcost',
            name='parkingSpot',
        ),
        migrations.AddField(
            model_name='parkingcost',
            name='parkingStation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spsmain.parkingstation'),
        ),
        migrations.AddField(
            model_name='parkingstation',
            name='ip',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
